### ISSUE TITLE
"modelnet40-c" dataset

### ISSUE THREAD

**Issue by wangxin-fighting** [jiachens/ModelNet40-C#13]
Hello, excuse me, could you please publish the download link for the "modelnet40-c" dataset? I tried the download method written in your readme file, but it was not successful, so I have to seek your help. Thank you very much!

**Comment by jiachens** [comment]
Thank you for your interest! Can you try to download the dataset from Google Drive or Zenodo?

**Comment by sx1999** [comment]
> Thank you for your interest! Can you try to download the dataset from Google Drive or Zenodo?

hi, the google drive link is not available now, can you share it again?

**Comment by jiachens** [comment]
Can you try to use Zenodo?

Thank you! Regards
