### ISSUE TITLE
Error occured when generating corruptions

### ISSUE THREAD

**Issue by NahyukLEE** [jiachens/ModelNet40-C#3]
Hi, thank you for your excellent paper and code release. I tried to generate ModelNet40-C but when I run `generate_c.py`, an error occured.

```
Traceback (most recent call last):
  File "data/generate_c.py", line 401, in <module>
    save_data(data[:,index,:], cor, sev)
  File "data/generate_c.py", line 360, in save_data
    new_data.append(MAP[corruption](data[i],severity))
TypeError: occlusion() takes 1 positional argument but 2 were given
```

I saw you comment some lines in `generate_c.py`, then can you give me some guides for 'occlusion' and 'lidar' corruptions?
```python
# if cor in ['occlusion', 'lidar','original']:
        #     continue
```

And, if I want to use this dataset for benchmark, should I download ModelNet40-C **directly** using `./download.sh modelnet40_c` rather than generate myself?

Thank you!

**Comment by jiachens** [comment]
Hi Nahyu,

Thank you so much for pointing out this bug, we will fix it soon. It would be simpler for you to directly download the ModelNet40-C using our script. 

Best,
Jiachen
