### ISSUE TITLE
Can I use this operator on KITII?

### ISSUE THREAD

**Issue by 853108389** [jiachens/ModelNet40-C#4]
Can I use this operator on KITII?

**Comment by jiachens** [comment]
Hi Niangao,

Thanks for your interest in our project. The point cloud in KITTI is essentially the "LiDAR" operator in our ModelNet40-C. However, you could still use the noise and transformation corruption operations for the object-level point cloud in KITTI. That is to say, you could first extract the point cloud of an object like a "car" or "cyclist", and then apply the operators in our code to them. Finally, you can put the corrupted point cloud back into the original KITTI point cloud.

Best,
Jiachen

**Comment by 853108389** [comment]
Thank you for your reply .
I have found the  "impulse_noise" function in in generate_c:
```
def impulse_noise(pointcloud, severity):
    ...
    return normalize(pointcloud)
```

The `normalize` function will  normalizes the point cloud so that the generated point cloud is very different from the original point cloud

What does this function do? And 
If I use it in Kitti, should I delete this function?

**Comment by jiachens** [comment]
the normalize function will normalize the point cloud into the edge-length-2 cube, and I don't think it will make the generated point cloud different from the original point cloud for ModelNet40-C.

For KITTI, you should not use it since it is an open-world dataset.

**Comment by 853108389** [comment]
Thank you
