### ISSUE TITLE
Would you opensource the code for "Adversarially Robust 3D Point Cloud Recognition Using Self-Supervisions"?

### ISSUE THREAD

**Issue by cuge1995** [jiachens/ModelNet40-C#7]

**Comment by cuge1995** [comment]
Thanks, could you send me the inference code and pre trained weight of Table 2?
We have achieved SOTA performance on 3D point cloud adversarial training, therefore, we want to compare your method in detail.

**Comment by cuge1995** [comment]
It would be greatly appreciated if you could provide this, it would save a lot of time in reproducing your work.

**Comment by cuge1995** [comment]
How to use standard and adversarial training in APF?
Do they appear with a probability of 0.5 during training?

**Comment by jiachens** [comment]
The download scripts for pretrained models from ModelNet40-C paper is the README.

For APF, we have two settings: 1. standard pretraining + adversarial fine-tuning. 2 adversarial pretraining + adversarial fine-tuning. You can also try to leverage some mixed training strategy.

Thanks.

**Comment by cuge1995** [comment]
> 

We want the weight of ""Adversarially Robust 3D Point Cloud Recognition Using Self-Supervisions"

**Comment by cuge1995** [comment]
In the Table 2 of "Adversarially Robust 3D Point Cloud Recognition Using Self-Supervisions", which setting do you used?

**Comment by jiachens** [comment]
The model weights are on the NVIDIA server and it is not easy to release them currently since I am busy with another internship.

In Table 2, for each setting there are two rows. Adversarial XXX means adversarial pre-training and XXX means standard pre-training.

Thanks.

**Comment by cuge1995** [comment]
Ok, I understand.
Thanks!

**Comment by jiachens** [comment]
We are also trying to propose new methods since we find some vulnerabilities of AT recently, but I look forward to your proposal. 
Keep in touch!

**Comment by cuge1995** [comment]
Can I add your wechat? my wechat is `cuge1995`
