### ISSUE TITLE
Using the code on Kitti datasets.

### ISSUE THREAD

**Issue by kkkcx** [jiachens/ModelNet40-C#9]
Hello,
Thanks for your great work！
I would like to ask why the layered phenomenon as shown in the figure occurs when the code is used to process Kitti datasets. 
Could you guide me here? 
Appreciate your work and the help. Thanks a lot！
<img width="479" alt="截屏2022-07-12 下午12 06 34" src="https://user-images.githubusercontent.com/50076963/178408661-c630cbad-f071-4afa-91fd-4f98e4316874.png">

**Comment by jiachens** [comment]
Which corruption operator are you using? Please provide more details.

**Comment by kkkcx** [comment]
After the normalization is removed, this phenomenon disappears. Thank you very much for your reply！

**Comment by jiachens** [comment]
Thank you for your interest in our project. Cheers!
